apiVersion: v1
kind: Service
metadata:
  name: service-client-svc
  labels:
    app: service-client
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 9080
  selector:
    app: service-client