apiVersion: v1
kind: Deployment
metadata:
  name: service-client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: service-client
    spec:
      containers:
      - name: service-client
        image: mdaros-spring-boot-labs/service-client:latest
        ports:
        - containerPort: 8080