apiVersion: v1
kind: Pod
metadata:
  name: service-client
  # Note that the Pod does not need to be in the same namespace as the loader.
  labels:
    app: service-client
spec:
  containers:
  - name: service-client
    image: service-client
    ports:
    - containerPort: 8080