apiVersion: v1
kind: Pod
metadata:
  name: service-provider
  # Note that the Pod does not need to be in the same namespace as the loader.
  labels:
    app: service-provider
spec:
  containers:
  - name: service-provider
    image: service-provider
    ports:
    - containerPort: 8080