apiVersion: v1
kind: Deployment
metadata:
  name: service-provider
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: service-provider
    spec:
      containers:
      - name: service-provider
        image: mdaros-spring-boot-labs/service-provider:latest
        ports:
        - containerPort: 8080