apiVersion: v1
kind: Service
metadata:
  name: service-provider-svc
  labels:
    app: service-provider
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 8080
  selector:
    app: service-provider